config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :inventories, only: [:index, :show]
  resources :products
  resources :product_types
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: %i[ show edit update destroy ]

  # GET /product_types or /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1 or /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types or /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: "Product type was successfully created." }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1 or /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: "Product type was successfully updated." }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1 or /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: "Product type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:name)
    end
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= form_with(model: product_type) do |form| %>
  <% if product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
        <% product_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.name %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_type.name %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>