config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :inventories, only: [:index, :show]
  resources :products
  resources :product_types
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = filter_transactions
    @total = 0
    @transactions.each do |transaction|
      @total += transaction.quantity * transaction.price_per_unity
    end
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @users = User.all
    @products = Product.all
  end

  # GET /transactions/1/edit
  def edit
    @users = User.all
    @products = Product.all
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    @transaction.price_per_unity *= -1 if buying?

    respond_to do |format|
      if @transaction.save
        update_inventory
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:quantity, :price_per_unity, :product_id, :user_id)
  end

  def update_inventory
    product = @transaction.product
    quantity_diff = @transaction.quantity
    quantity_diff *= -1 unless buying?
    product.quantity += quantity_diff
    product.save
  end

  def filter_transactions
    return Transaction.where('created_at > ?', params[:since]) if params[:since].present?
    return Transaction.all unless params[:transaction_type].present?
    return Transaction.where('price_per_unity <= 0') if buying?
    Transaction.where('price_per_unity > 0')
  end

  def buying?
    params[:transaction_type] == 'buy'
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, @users,:id,:name %>
  </div>

  <div class="field">
    <label>Tipo de transação</label>

    <select name="transaction_type" style="display: block">
      <option value="buy">Compra</option>
      <option value="sell">Venda</option>
    </select>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id, @products,:id,:name %>
  </div>

  <div class="field">
    <%= form.label :price_per_unity %>
    <%= form.text_field :price_per_unity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Price per unity</th>
      <th>Product</th>
      <th>User</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.quantity %></td>
        <td><%= transaction.price_per_unity %></td>
        <td><%= transaction.product.product_type.name %> - <%= transaction.product.name %></td>
        <td><%= transaction.user.name %></td>
        <td><%= transaction.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td><b>Total:</b></td>
      <td><b><%= @total  %></b></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @transaction.quantity %>
</p>

<p>
  <strong>Price per unity:</strong>
  <%= @transaction.price_per_unity %>
</p>

<p>
  <strong>Product:</strong>
  <%= @transaction.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @transaction.user_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>